### ISSUE TITLE
.flayignore isn't working

### ISSUE THREAD

**Issue by giedriusr** [mmozuras/pronto-flay#7]
Hello,

I've just tried to setup `.flayignore` in my project's repository with the content below:
```
spec/**/*
```
and running it with the command `flay spec/` it works and doesn't throw any warnings, but when I run `pronto run`it says about duplications. Am I missing something? Anyone else has the same issue?

**Comment by mmozuras** [comment]
> Skips files matched via patterns in .flayignore (subset format of .gitignore).

@giedriusr it works as expected on Pronto side. `.flayignore` has its own way for pattern matching. For example, we use `*_spec.rb`. I couldn't find decent documentation, you can try to figure out more from the source code: https://github.com/seattlerb/flay/blob/master/lib/flay.rb#L153

**Comment by giedriusr** [comment]
@mmozuras their documentation says it works same way as .gitignore, but thanks.

**Comment by mmozuras** [comment]
> **subset** format of .gitignore

@giedriusr no problem :bow:
