### ISSUE TITLE
Feature: Adding information about mass to issue message

### ISSUE THREAD

**Issue by jekuta** [mmozuras/pronto-flay#8]
Besides pointing out the files that have similar code, Flay gives us a mass score indicating the amount of duplicated code. How about adding the score to the message as well?

Something like this:
```
app/models/post.rb:17 E: Identical code found in post.rb:5, post.rb:11, post.rb:17 (mass = 144)
```

@mmozuras What do think? I already went ahead and created a PR for this small change.

**Comment by mmozuras** [comment]
@jekuta I checked and it now matches more closely to how `flay` outputs messages. Good idea, thanks! 🙇
